-- Seed products migrated from the original data/products.json.
-- Run after 03_storage.sql. Safe to re-run (upsert on id).

insert into products (id, name, category, series, image_url, description, price, in_stock, whatsapp_number, specs, is_featured, sort_order) values
  ('classical-sitar', 'Classical Sitar', 'string', 'String Instruments', './assets/images/hero/sitar-hero.png', 'Premium handcrafted sitar with traditional design. Features a resonating gourd body, intricate decorative work, and superior tonal quality. Perfect for professional performers and serious students of Indian classical music.', 'Rs. 45,000', true, '9779800000000', '{"Type": "Classical Sitar", "Body Material": "Toon Wood with Gourd", "Strings": "7 Main + 13 Sympathetic", "Finish": "Hand-polished Natural", "Case Included": "Yes (Padded)"}'::jsonb, true, 0),
  ('concert-sitar', 'Concert Sitar', 'string', 'String Instruments', './assets/images/hero/sitar-hero.png', 'Professional grade concert sitar designed for stage performances. Enhanced resonance and projection with premium quality materials.', 'Rs. 75,000', true, '9779800000000', '{"Type": "Concert Sitar", "Body Material": "Premium Toon Wood", "Strings": "7 Main + 13 Sympathetic", "Finish": "Lacquer Polish", "Case Included": "Yes (Hard Case)"}'::jsonb, true, 1),
  ('tanpura', 'Tanpura', 'string', 'String Instruments', './assets/images/hero/sitar-hero.png', 'Essential drone instrument for classical music practice and performances. Creates the perfect harmonic backdrop.', 'Rs. 32,000', true, '9779800000000', '{"Type": "Tanpura", "Body": "Gourd", "Strings": "4 Steel", "Finish": "Natural Polish", "Height": "48 inches"}'::jsonb, true, 2),
  ('sarangi', 'Sarangi', 'string', 'String Instruments', './assets/images/hero/sitar-hero.png', 'Bowed string instrument known for its ability to closely imitate the human voice. For advanced players.', 'Rs. 42,000', true, '9779800000000', '{"Type": "Sarangi", "Body": "Toon Wood", "Strings": "3 Main + 37 Sympathetic", "Bow": "Horsehair", "Case": "Included"}'::jsonb, true, 3),
  ('professional-tabla', 'Professional Tabla Set', 'percussion', 'Percussion', './assets/images/hero/tabla-hero.png', 'Delhi style tabla pair crafted by master artisans. Features sheesham wood dayan and copper bayan with traditional tuning blocks.', 'Rs. 35,000', true, '9779800000000', '{"Type": "Delhi Style Tabla Set", "Dayan Material": "Sheesham Wood", "Bayan Material": "Copper", "Heads": "Goat Skin", "Accessories": "Hammer, Rings, Cover"}'::jsonb, true, 4),
  ('student-tabla', 'Student Tabla Set', 'percussion', 'Percussion', './assets/images/hero/tabla-hero.png', 'Entry-level tabla set perfect for beginners. Quality construction at an affordable price point.', 'Rs. 15,000', true, '9779800000000', '{"Type": "Student Tabla Set", "Dayan Material": "Mango Wood", "Bayan Material": "Steel", "Heads": "Goat Skin", "Accessories": "Hammer, Rings"}'::jsonb, false, 5),
  ('dholak-drum', 'Dholak Drum', 'percussion', 'Percussion', './assets/images/products/dholak.png', 'Traditional barrel-shaped drum for folk music and bhajans. Rope-tuned with quality goat skin heads.', 'Rs. 8,500', true, '9779800000000', '{"Type": "Folk Dholak", "Shell": "Mango Wood", "Heads": "Goat Skin", "Tuning": "Rope & Ring", "Size": "18 inches"}'::jsonb, false, 6),
  ('bansuri-flute', 'Professional Bansuri', 'wind', 'Wind Instruments', './assets/images/hero/bansuri-flute.png', 'Professional bamboo flute crafted from aged bamboo. Precise tuning for classical music performances.', 'Rs. 8,000', true, '9779800000000', '{"Type": "Base Bansuri", "Material": "Aged Bamboo", "Scale": "E Base", "Holes": "6 + 1", "Length": "32 inches"}'::jsonb, false, 7),
  ('bansuri-set', 'Bansuri Set (3 Flutes)', 'wind', 'Wind Instruments', './assets/images/hero/bansuri-flute.png', 'Set of three bansuris in different scales. Perfect for students and practitioners.', 'Rs. 12,000', true, '9779800000000', '{"Type": "Bansuri Set", "Scales": "E, G, A", "Material": "Bamboo", "Includes": "Carry Case"}'::jsonb, false, 8),
  ('classical-shehnai', 'Classical Shehnai', 'wind', 'Wind Instruments', './assets/images/products/shehnai.png', 'Traditional shehnai made from quality teak wood. Produces the authentic ceremonial sound.', 'Rs. 15,000', true, '9779800000000', '{"Type": "Classical Shehnai", "Material": "Teak Wood", "Bell": "Brass", "Reeds": "2 Included", "Case": "Included"}'::jsonb, false, 9),
  ('harmonium-deluxe', 'Harmonium Deluxe', 'keyboard', 'Keyboard', './assets/images/hero/harmonium-hero.png', 'Scale changer harmonium with 3.5 octaves. Features multiple reed sets and coupler for rich, full sound.', 'Rs. 55,000', true, '9779800000000', '{"Type": "Scale Changer", "Keys": "42 (3.5 Octaves)", "Reeds": "Triple Reed", "Bellows": "7 Fold", "Body": "Teak Wood"}'::jsonb, true, 10),
  ('portable-harmonium', 'Portable Harmonium', 'keyboard', 'Keyboard', './assets/images/hero/harmonium-hero.png', 'Compact folding harmonium ideal for travel and small gatherings. Lightweight yet produces full sound.', 'Rs. 28,000', true, '9779800000000', '{"Type": "Folding/Portable", "Keys": "39 (3.25 Octaves)", "Reeds": "Double Reed", "Bellows": "5 Fold", "Body": "Teak Wood"}'::jsonb, true, 11),
  ('electric-tanpura', 'Electric Tanpura', 'electronic', 'Electronic Instruments', './assets/images/hero/harmonium-hero.png', 'Digital tanpura with authentic sound samples. Portable and perfect for practice sessions.', 'Rs. 12,000', true, '9779800000000', '{"Type": "Electronic Tanpura", "Modes": "Male/Female Voice", "Power": "AC/Battery", "Speaker": "Built-in", "Controls": "Pitch, Tempo, Volume"}'::jsonb, false, 12),
  ('tabla-machine', 'Digital Tabla Machine', 'electronic', 'Electronic Instruments', './assets/images/hero/tabla-hero.png', 'Electronic tabla with 100+ preset rhythms. Perfect for solo practice and performances.', 'Rs. 18,000', true, '9779800000000', '{"Type": "Digital Tabla", "Presets": "100+ Taals", "Tempo Range": "10-300 BPM", "Output": "Headphone + Line Out", "Display": "LCD"}'::jsonb, false, 13),
  ('instrument-case', 'Premium Instrument Case', 'accessories', 'Accessories', './assets/images/hero/sitar-hero.png', 'Heavy-duty padded case for sitar and similar instruments. Waterproof with shoulder strap.', 'Rs. 5,500', true, '9779800000000', '{"Type": "Hard Case", "Material": "Oxford Fabric", "Padding": "25mm Foam", "Waterproof": "Yes", "Pockets": "3 Accessory Pockets"}'::jsonb, false, 14),
  ('tabla-cover-set', 'Tabla Cover Set', 'accessories', 'Accessories', './assets/images/hero/tabla-hero.png', 'Protective covers for tabla pair with padded interior. Includes hammer pocket.', 'Rs. 1,800', true, '9779800000000', '{"Type": "Tabla Covers", "Material": "Rexine", "Set Includes": "Dayan Cover, Bayan Cover", "Padding": "Yes", "Hammer Pocket": "Yes"}'::jsonb, false, 15),
  ('tuning-hammer', 'Professional Tuning Hammer', 'accessories', 'Accessories', './assets/images/hero/tabla-hero.png', 'Heavy-duty brass tuning hammer for tabla. Ergonomic wooden handle.', 'Rs. 800', true, '9779800000000', '{"Type": "Tuning Hammer", "Head": "Brass", "Handle": "Rosewood", "Weight": "250g", "Length": "18cm"}'::jsonb, false, 16),
  ('mpro-studio-mic', 'Mpro Studio Microphone', 'mpro', 'Mpro Professional', './assets/images/hero/harmonium-hero.png', 'Professional condenser microphone designed for recording Indian classical instruments.', 'Rs. 25,000', true, '9779800000000', '{"Type": "Condenser Mic", "Pattern": "Cardioid", "Frequency": "20Hz-20kHz", "Connection": "XLR", "Includes": "Shock Mount, Pop Filter"}'::jsonb, true, 17),
  ('mpro-audio-interface', 'Mpro Audio Interface', 'mpro', 'Mpro Professional', './assets/images/hero/harmonium-hero.png', '2-channel USB audio interface for home recording. Low latency with premium preamps.', 'Rs. 35,000', true, '9779800000000', '{"Type": "Audio Interface", "Inputs": "2 XLR/TRS Combo", "Outputs": "2 TRS + Headphone", "Sample Rate": "192kHz", "Connection": "USB-C"}'::jsonb, true, 18)
on conflict (id) do update set
  name=excluded.name, category=excluded.category, series=excluded.series,
  image_url=excluded.image_url, description=excluded.description, price=excluded.price,
  in_stock=excluded.in_stock, whatsapp_number=excluded.whatsapp_number,
  specs=excluded.specs, is_featured=excluded.is_featured, sort_order=excluded.sort_order;
